name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run a one-line script
      run: echo "Push checks are now active!"

    - name: Run a multi-line script
      run: |
        echo "Validating repository structure..."
        ls -R
